export const REQUEST_API_DATA = "REQUEST_API_DATA"
export const RECEIVE_API_DATA = "RECEIVE_API_DATA"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const ADD_FAVORITE = "ADD_FAVORITE"